[problem]                           # ode problem
_name_ = "fpu"
omega = 300.0

[algorithm]                         # data generation algorithm
# _name_ = "trajensemble"
# sigma = 1e-1
# n_chains = 5
# n_steps_per_chain = 10

_name_ = "hmc-H0"  
sigma = 1e-1
n_chains = 5
n_trans_per_chain = 10
n_steps_per_trans = 1
with_rejection = true

# _name_ = "hmc"
# beta = 1.0
# n_chains = 5
# n_trans_per_chain = 10
# n_steps_per_trans = 1
# with_rejection = true

[integration]
dt = 4e-1                           # time interval 
nsteps = 65536                      # number of steps per interval
method = "CalvoSanz4"               # solver method
use_float64x4 = true               # use Float64x4 
