# path to root directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
data_dir: ${oc.env:DATA_DIR}

# path to logging directory
log_dir: ${paths.root_dir}/deep_learning/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}