i2h:
  _target_: torch.nn.Identity

h2h:
  _target_: networks.equiv.EquivarianceNetwork
  N: 7
  d: 2
  n_hidden_nodes: 200
  n_hidden_layers: 3
  activation:
    _target_: torch.nn.ELU
  use_bn: False

h2o:
  _target_: torch.nn.Identity