# @package _global_

# default debugging setup, other debugging configs can inherit from this one

# overwrite task name so debugging logs are stored in separate folder
task_name: debug

# disable callbacks and loggers during debugging
defaults:
  - override /callbacks: 
    - fixed_seq_weights
    - tqdm_progress_bar
    # - model_checkpoint
  - override /module/scheduler: none
  - override /trainer: gpu

loggers: null

# runs 1 full epoch
trainer:
  max_epochs: 1
  enable_checkpointing: False

# turn off testing
test: False