# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datamodule: default
  - module: solnmap
  - callbacks:
    - model_checkpoint
    - lr_monitor
    - fixed_seq_weights
    - metrics_logger
    - tqdm_progress_bar
  - loggers: 
    - wandb
  - trainer: default
  - paths: default
  - hydra: default
  
  # experiment configs allow for version control of specific hyperparameters
  # e.g. the best hyperparameters for given model and datamodule
  - experiment: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# seed for random number generators in pytorch, numpy and python.random
seed: 42

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# task name, determines output directory path
task_name: train

# name and id of the run, accessed by loggers and determine output directory path
run_name: ${get_run_name:${resume_from_ckpt}}
run_id: ${get_run_id:${resume_from_ckpt}}

# provide checkpoint path to resume training
resume_from_ckpt: null 

# initialize model with checkpoint  
init_model_ckpt: null

# freeze layers
freeze_encoder_decoder: False